name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Print VTK folder contents
      run: |
        git submodule update --init --recursive
        cd $GITHUB_WORKSPACE/vtk
        ls -l
    - name: Install dependencies
      if: contains('disabled', 'true')
      run: |
        sudo apt update
        sh $GITHUB_WORKSPACE/platforms/ubuntu/18.04/apt_install_dependency.sh
    - name: Print mono version
      run: mono --version
    - name: Configure CMAKE
      run: sh $GITHUB_WORKSPACE/platforms/ubuntu/18.04/cmake_configure.sh
    - name: Build EmguCV
      run: make
    - name: Print bin folder contents
      run: |
        cd $GITHUB_WORKSPACE/bin
        ls -l
    - name: Run the examples
      run: |
        cd $GITHUB_WORKSPACE/bin
        export LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH
        mono Example.PlanarSubdivision.monoexe


